name: ekf_employees
description: EKF test app
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  datetime_picker_formfield: ^1.0.0
  intl: ^0.16.1
  path_provider: ^1.6.10
  provider: ^4.1.2
  sembast: ^2.4.4+1
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true